### ISSUE TITLE
Installation of Filebeat on Openshift 4.8.x errors with spec.template.spec.containers[0].image: Required value

### ISSUE THREAD

**Issue by MastanaGuru** [elastic/cloud-on-k8s#5564]
**What did you do?**
Install Filebeat using the [Filebeat recipe](https://github.com/elastic/cloud-on-k8s/blob/2.1/config/recipes/beats/filebeat_no_autodiscover.yaml) 

**What did you expect to see?**
Filebeat daemonset being created and running. 

**What did you see instead? Under which circumstances?**
Installation fails with 
`Reconciliation error: DaemonSet.apps "apps-filebeat-beat-filebeat" is invalid: spec.template.spec.containers[0].image: Required value`

**Environment**
ECK verison 2.1.0
Filebeat version 8.0.0

* Kubernetes information:
Openshift 4.8.x 

* Resource definition:
```
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: apps-filebeat
  namespace: elastic-elk
spec:
  type: filebeat
  version: 8.0.0
  configRef:
    secretName: apps-filebeat-config
  secureSettings:
    - secretName: elasticsearch-es-http-certs-internal
    - secretName: apps-pks-certs
  serviceAccountName: apps-filebeat
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        initContainers:
        - name: run-chcon
          command:
          - sh
          - -c
          - |
            chcon -R -t svirt_sandbox_file_t /usr/share/filebeat/data/
        containers:
        - name: filebeat
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers

**Comment by barkbay** [comment]
I have deployed a very similar manifest on OpenShift 4.10.6 without issue:

```yaml
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: apps-filebeat
  namespace: elastic-elk
spec:
  type: filebeat
  version: 8.0.0
  configRef:
    secretName: apps-filebeat-config
  secureSettings:
    - secretName: elasticsearch-credentials
  serviceAccountName: apps-filebeat
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        securityContext:
          runAsUser: 0
        containers:
          - name: filebeat
            resources:
              limits:
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi
            securityContext:
              runAsUser: 0
              privileged: true
            volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
        volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
```

Note that I have removed the `run-chcon` init container, I'm not sure that the SELinux context on the host should be changed, I also added a `securityContext` at the Pod level.

```
> k get beat,ds,pods
NAME                                     HEALTH   AVAILABLE   EXPECTED   TYPE       VERSION   AGE
beat.beat.k8s.elastic.co/apps-filebeat   green    6           6          filebeat   8.0.0     13m

NAME                                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/apps-filebeat-beat-filebeat   6         6         6       6            6           <none>          10m

NAME                                    READY   STATUS    RESTARTS   AGE
pod/apps-filebeat-beat-filebeat-chtp5   1/1     Running   0          6m11s
pod/apps-filebeat-beat-filebeat-k4x4f   1/1     Running   0          5m55s
pod/apps-filebeat-beat-filebeat-mt77f   1/1     Running   0          6m28s
pod/apps-filebeat-beat-filebeat-rmmcr   1/1     Running   0          6m19s
pod/apps-filebeat-beat-filebeat-s7sbq   1/1     Running   0          6m36s
pod/apps-filebeat-beat-filebeat-v2l98   1/1     Running   0          6m3s
```

I can try on OpenShift `4.8.x` but I think the OpenShift version is unlikely to be the problem.

**Comment by barkbay** [comment]
Just did the same test on OpenShift 4.8.36 and it's also working as expected.

**Comment by MastanaGuru** [comment]
Hi @barkbay , thanks for the response.
I uninstalled and redeployed everything (changed stack version to 8.1.0), but still getting the same error.  I also don't see anything in the logs. Any help much appreciated. 

```
$ oc get events
LAST SEEN   TYPE      REASON                OBJECT      MESSAGE
46m         Warning   ReconciliationError   beat/apps   Reconciliation error: DaemonSet.apps "apps-beat-filebeat" is invalid: spec.template.spec.containers[0].image: Required value
```

```
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: apps
   namespace: elastic-elk
spec:
  type: filebeat
  version: 8.1.0
  configRef:
    secretName: apps-filebeat-config
  secureSettings:
    - secretName: elasticsearch-es-http-certs-internal
  serviceAccountName: apps-filebeat
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        securityContext:
          runAsUser: 0
        containers:
          - name: apps
            resources:
              limits:
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi
            securityContext:
              runAsUser: 0
              privileged: true
            volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
        volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
```

**Comment by barkbay** [comment]
> I uninstalled and redeployed everything (changed stack version to 8.1.0), but still getting the same error.

This is not the same manifest as the one you provided in the first comment. Container must be named `filebeat`:

```diff
24c24
<           - name: apps
---
>           - name: filebeat
```

**Comment by MastanaGuru** [comment]
Changing the container name to "filebeat", I am not getting the "spec.template.spec.containers[0].image: Required value. But another error while pod creation. (We will be deploying Filebeat only on worker nodes).
```
Error creating: pods "apps-beat-filebeat-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider "pipelines-scc": Forbidden: not usable by user or serviceaccount, provider restricted: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used, spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[5]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.initContainers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000950000, 1000959999], spec.initContainers[0].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used, spec.containers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000950000, 1000959999], spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed, spec.containers[0].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "log-collector-scc": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount, provider "trident": Forbidden: not usable by user or serviceaccount]
```

```
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: apps
  namespace: elastic-elk
spec:
  type: filebeat
  version: 8.1.0
  configRef:
    secretName: apps-filebeat-config
  secureSettings:
    - secretName: elasticsearch-es-http-certs-internal
  serviceAccountName: apps-filebeat
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        securityContext:
          runAsUser: 0
        containers:
          - name: filebeat
            resources:
              limits:
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi
            securityContext:
              runAsUser: 0
              privileged: true
            volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
        volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apps-filebeat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apps-filebeat
subjects:
- kind: ServiceAccount
  name: apps-filebeat
  namespace: elastic-elk



apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: apps-filebeat
  name: apps-filebeat
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list


apiVersion: v1
imagePullSecrets:
- name: apps-filebeat-dockercfg-x2g4f
kind: ServiceAccount
metadata:
  name: apps-filebeat
  namespace: elastic-elk
secrets:
- name: apps-filebeat-dockercfg-x2g4f
- name: apps-filebeat-token-2n5p4
```

**Comment by barkbay** [comment]
> But another error while pod creation.
>  [...] unable to validate against any security context constraint

Did you add the service account to an SCC as explained [in the documentation](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-openshift-beats.html#k8s-openshift-beats)?

**Comment by MastanaGuru** [comment]
Yes.

```
apiVersion: v1
imagePullSecrets:
- name: apps-filebeat-dockercfg-x2g4f
kind: ServiceAccount
metadata:
  name: apps-filebeat
  namespace: elastic-elk
secrets:
- name: apps-filebeat-dockercfg-x2g4f
- name: apps-filebeat-token-2n5p4
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:privileged
  namespace: elastic-elk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: apps-filebeat
  namespace: elastic-elk
```

**Comment by MastanaGuru** [comment]
Thanks @barkbay, that fixed it. Really appreciate all your help.

**Comment by barkbay** [comment]
Glad to hear it helped 👍 
Feel free to use our [discuss forum](https://discuss.elastic.co/c/orchestration/eck/79) if you have any further trouble.

Thanks
